version: "3"
services:
  moodledb:
    container_name: moodledb
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: password
    volumes:
      - moodledb:/var/lib/postgresql/data

  moodle:
    container_name: moodle
    build:
      context: moodle
      args:
        - MOODLE_VERSION=MOODLE_311_STABLE
    depends_on:
      - moodledb
    restart: on-failure
    environment:
      MOODLE_DOCKER_DBTYPE: pgsql
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: password
      MOODLE_DOCKER_ADMINPASS: password
      MOODLE_DOCKER_WEB_HOST: localhost
      MOODLE_DOCKER_WEB_PORT: 80
      ENABLE_XDEBUG: 1
    volumes:
      - ./moodle/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./moodle/block_opencast:/var/www/html/blocks/opencast
      - ./moodle/filter_opencast:/var/www/html/filter/opencast
      - ./moodle/mod_opencast:/var/www/html/mod/opencast
      - ./moodle/repository_opencast:/var/www/html/repository/opencast
      - ./moodle/tool_opencast:/var/www/html/admin/tool/opencast
    ports:
      - "80:80"

volumes:
  moodledb: { }
